Removed reference to spec_helper.rb.
It was coming up with an error (below) that I don't know how
to troubleshoot.

./spec_helper.rb:29: undefined method `include_chain_clauses_in_custom_matcher_descriptions=' for #<RSpec::Expectations::Configuration:0x7f823c2f3f08> (NoMethodError)
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:580:in `expect_with'
  from ./spec_helper.rb:21
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core.rb:154:in `configure'
  from ./spec_helper.rb:17
  from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
  from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
  from /home/leam/lang/git/CT_Character_Generator/spec/lib/marine_spec.rb:1
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
  from /usr/lib/ruby/gems/1.8/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `autorun'
  from /usr/bin/rspec:19